// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
const firebaseConfig = {
  apiKey: "AIzaSyDCNACpuqxisTfVfCFmg8n-He8JP9LrDV0",
  authDomain: "dsm-3a-8da27.firebaseapp.com",
  projectId: "dsm-3a-8da27",
  storageBucket: "dsm-3a-8da27.appspot.com",
  messagingSenderId: "1058015839648",
  appId: "1:1058015839648:web:9b423e8cdf084f7e94d0c5"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
